# **Notebook 3 - Basket Analysis**

Afonso Fernandes 20241710, Lourenço Lima 20241711, Lucas Casimiro 20241796

## Imports

In [37]:
import os
import sys
import warnings
from pathlib import Path
import pandas as pd

def _find_project_root(start, marker="requirements.txt"):
    path = Path(start).resolve()
    for candidate in [path] + list(path.parents):
        if (candidate / marker).exists():
            return str(candidate)
    raise RuntimeError(f"Could not find project root (marker={marker!r}, searched from {start})")

PROJECT_ROOT = _find_project_root(os.path.abspath("."))
os.chdir(PROJECT_ROOT)
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

warnings.filterwarnings("ignore")

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
import seaborn as sns
import math
from sklearn.preprocessing import RobustScaler

from functions.eda import *
from functions.preprocessing import *
from functions.basket import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# **1. Merging data**

In [39]:
customer_basket = pd.read_csv('data/customer_basket.csv')
customer = pd.read_csv('data/ci_clustered.csv')

# **2. Dataframe by cluster**

In [40]:
cluster_dataframes = {
    cluster: group
    for cluster, group in customer.groupby("final_cluster_label")
}

loyal_core_spenders = cluster_dataframes.get('Loyal core spenders')
bargain_hunters = cluster_dataframes.get('Bargain hunters')
big_families = cluster_dataframes.get('Big families (big spenders)')
vegans = cluster_dataframes.get('Vegans')
tech_enthusiasts = cluster_dataframes.get('Tech enthusiasts')
karens = cluster_dataframes.get('Karens')
gamers = cluster_dataframes.get('Gamers')

## Parameter by cluster

In [41]:
params_by_cluster = {
    "Loyal core spenders": {
        "min_support": 0.02,
        "min_threshold": 1,
        "min_confidence": 0.10
    },
    "Vegans": {
        "min_support": 0.01,
        "min_threshold": 1,
        "min_confidence": 0.10
    },
    "Bargain hunters": {
        "min_support": 0.01,
        "min_threshold": 1,
        "min_confidence": 0.10
    },
    "Karens": {
        "min_support": 0.008,
        "min_threshold": 1,
        "min_confidence": 0.08
    },
    "Tech enthusiasts": {
        "min_support": 0.006,
        "min_threshold": 1,
        "min_confidence": 0.08
    },
    "Big families (big spenders)": {
        "min_support": 0.006,
        "min_threshold": 1,
        "min_confidence": 0.08
    },
    "Gamers": {
        "min_support": 0.004,
        "min_threshold": 1,
        "min_confidence": 0.06
    }
}

# **3. Association rules**

In [42]:
# 2. Reload do basket.py
import importlib
import functions.basket as basket_module

importlib.reload(basket_module)

generate_rules_for_all_clusters = basket_module.generate_rules_for_all_clusters
generate_association_rules = basket_module.generate_association_rules

In [ ]:
all_cluster_rules = generate_rules_for_all_clusters(
    cluster_dataframes=cluster_dataframes,
    basket=customer_basket,
    params_by_cluster=params_by_cluster
)

for cluster_name, rules in all_cluster_rules.items():
    print(f"CLUSTER: {cluster_name}")

    if rules.empty:
        print("No rules found.")
    else:
        display(rules.head(30))

======================================================================
CLUSTER: Bargain hunters
======================================================================

,antecedents,consequents,support,confidence,lift
0,"frozenset({energy drink, laptop})",frozenset({bluetooth headphones}),0.010753,0.458716,3.777499
1,"frozenset({protein bar, bluetooth headphones})",frozenset({energy drink}),0.010251,0.432024,3.497816
2,"frozenset({bluetooth headphones, laptop})",frozenset({energy drink}),0.010753,0.426136,3.450146
3,"frozenset({protein bar, energy drink})",frozenset({bluetooth headphones}),0.010251,0.414493,3.413326
4,frozenset({bluetooth headphones}),"frozenset({energy drink, airpods})",0.025591,0.210744,3.390860
5,"frozenset({energy drink, airpods})",frozenset({bluetooth headphones}),0.025591,0.411765,3.390860
6,"frozenset({protein bar, airpods})",frozenset({energy drink}),0.016774,0.417112,3.377084
7,frozenset({energy drink}),"frozenset({protein bar, airpods})",0.016774,0.135810,3.377084
8,"frozenset({samsung galaxy 10, airpods})",frozenset({energy drink}),0.010824,0.409214,3.313138
9,frozenset({energy drink}),"frozenset({bluetooth headphones, airpods})",0.025591,0.207197,3.310876
10,"frozenset({bluetooth headphones, airpods})",frozenset({energy drink}),0.025591,0.408935,3.310876
11,"frozenset({airpods, laptop})",frozenset({bluetooth headphones}),0.015842,0.398917,3.285060
12,frozenset({bluetooth headphones}),"frozenset({airpods, laptop})",0.015842,0.130460,3.285060
13,"frozenset({airpods, ring light})",frozenset({bluetooth headphones}),0.010538,0.385827,3.177263
14,"frozenset({airpods, ring light})",frozenset({energy drink}),0.010681,0.391076,3.166287
15,"frozenset({airpods, iphone 10})",frozenset({bluetooth headphones}),0.014122,0.381783,3.143962
16,frozenset({bluetooth headphones}),"frozenset({airpods, iphone 10})",0.014122,0.116293,3.143962
17,frozenset({bluetooth headphones}),"frozenset({protein bar, airpods})",0.015269,0.125738,3.126638
18,"frozenset({protein bar, airpods})",frozenset({bluetooth headphones}),0.015269,0.379679,3.126638
19,"frozenset({energy bar, airpods})",frozenset({energy drink}),0.015054,0.385321,3.119692
20,frozenset({energy drink}),"frozenset({energy bar, airpods})",0.015054,0.121880,3.119692
21,"frozenset({protein bar, energy drink})",frozenset({airpods}),0.016774,0.678261,3.105264
22,"frozenset({energy drink, ring light})",frozenset({airpods}),0.010681,0.677273,3.100740
23,"frozenset({airpods, pancakes})",frozenset({bluetooth headphones}),0.013118,0.374233,3.081790
24,frozenset({bluetooth headphones}),"frozenset({airpods, pancakes})",0.013118,0.108028,3.081790
25,frozenset({energy drink}),"frozenset({airpods, pancakes})",0.013262,0.107371,3.063034
26,"frozenset({airpods, pancakes})",frozenset({energy drink}),0.013262,0.378323,3.063034
27,frozenset({airpods}),"frozenset({bluetooth headphones, energy drink})",0.025591,0.117164,3.037999
28,"frozenset({bluetooth headphones, energy drink})",frozenset({airpods}),0.025591,0.663569,3.037999
29,"frozenset({bluetooth headphones, ring light})",frozenset({airpods}),0.010538,0.659193,3.017965

======================================================================
CLUSTER: Big families (big spenders)
======================================================================

,antecedents,consequents,support,confidence,lift
0,"frozenset({fresh bread, black tea})","frozenset({salt, cereals})",0.006843,0.111959,1.860202
1,"frozenset({salt, cereals})","frozenset({fresh bread, black tea})",0.006843,0.113695,1.860202
2,"frozenset({honey, milk})","frozenset({oatmeal, cereals})",0.007465,0.166090,1.857319
3,"frozenset({oatmeal, cereals})","frozenset({honey, milk})",0.007465,0.083478,1.857319
4,frozenset({vegetables mix}),"frozenset({eggs, honey})",0.006687,0.161049,1.842603
5,"frozenset({honey, cereals, milk})",frozenset({oatmeal}),0.007465,0.393443,1.835875
6,"frozenset({eggs, nonfat milk})",frozenset({oatmeal}),0.006843,0.392857,1.833143
7,"frozenset({salt, honey})",frozenset({oil}),0.007154,0.219048,1.824451
8,"frozenset({eggs, vegetables mix})",frozenset({honey}),0.006687,0.383929,1.816527
9,frozenset({vegetables mix}),"frozenset({butter, honey})",0.006376,0.153558,1.772672
10,"frozenset({green tea, milk})","frozenset({eggs, butter})",0.006532,0.253012,1.764498
11,frozenset({nonfat milk}),"frozenset({eggs, oatmeal})",0.006843,0.151203,1.754934
12,"frozenset({salt, cereals})","frozenset({tea, fresh bread})",0.009642,0.160207,1.751920
13,"frozenset({tea, fresh bread})","frozenset({salt, cereals})",0.009642,0.105442,1.751920
14,"frozenset({eggs, butter, milk})",frozenset({green tea}),0.006532,0.196262,1.735850
15,frozenset({whole weat flour}),frozenset({chili}),0.010109,0.083120,1.735269
16,frozenset({chili}),frozenset({whole weat flour}),0.010109,0.211039,1.735269
17,frozenset({pet food}),"frozenset({butter, tea})",0.006532,0.144330,1.731420
18,"frozenset({green tea, oatmeal})","frozenset({eggs, cereals})",0.006376,0.266234,1.730923
19,"frozenset({green tea, oatmeal})",frozenset({black tea}),0.006376,0.266234,1.725689
20,"frozenset({salt, fresh bread})","frozenset({tea, cereals})",0.009642,0.151961,1.723294
21,"frozenset({tea, cereals})","frozenset({salt, fresh bread})",0.009642,0.109347,1.723294
22,"frozenset({eggs, mashed potato})",frozenset({honey}),0.006843,0.360656,1.706414
23,"frozenset({cereals, black tea})","frozenset({butter, sandwich})",0.006221,0.095694,1.704463
24,"frozenset({butter, sandwich})","frozenset({cereals, black tea})",0.006221,0.110803,1.704463
25,"frozenset({oatmeal, honey})","frozenset({cereals, milk})",0.007465,0.142012,1.703612
26,"frozenset({cereals, milk})","frozenset({oatmeal, honey})",0.007465,0.089552,1.703612
27,"frozenset({green tea, fresh bread})","frozenset({butter, tea})",0.006687,0.141447,1.696841
28,"frozenset({butter, tea})","frozenset({green tea, fresh bread})",0.006687,0.080224,1.696841
29,"frozenset({cereals, tea, milk})",frozenset({oatmeal}),0.006998,0.362903,1.693373

======================================================================
CLUSTER: Gamers
======================================================================

,antecedents,consequents,support,confidence,lift
0,"frozenset({airpods, iphone 10})","frozenset({bluetooth headphones, energy drink})",0.004024,0.209677,9.154969
1,"frozenset({bluetooth headphones, energy drink})","frozenset({airpods, iphone 10})",0.004024,0.175676,9.154969
2,"frozenset({energy drink, airpods})","frozenset({bluetooth headphones, iphone 10})",0.004024,0.106557,9.060181
3,"frozenset({bluetooth headphones, iphone 10})","frozenset({energy drink, airpods})",0.004024,0.342105,9.060181
4,"frozenset({bluetooth headphones, airpods})","frozenset({energy drink, iphone 10})",0.004024,0.117117,8.800126
5,"frozenset({energy drink, iphone 10})","frozenset({bluetooth headphones, airpods})",0.004024,0.302326,8.800126
6,"frozenset({bluetooth headphones, energy drink})","frozenset({protein bar, airpods})",0.004952,0.216216,8.123193
7,"frozenset({protein bar, airpods})","frozenset({bluetooth headphones, energy drink})",0.004952,0.186047,8.123193
8,"frozenset({megaman zero 3, airpods})",frozenset({bluetooth headphones}),0.004024,0.541667,7.743916
9,"frozenset({protein bar, bluetooth headphones})","frozenset({energy drink, airpods})",0.004952,0.285714,7.566745
10,"frozenset({energy drink, airpods})","frozenset({protein bar, bluetooth headphones})",0.004952,0.131148,7.566745
11,"frozenset({energy drink, airpods, iphone 10})",frozenset({bluetooth headphones}),0.004024,0.520000,7.434159
12,"frozenset({bluetooth headphones, final fantasy...",frozenset({airpods}),0.006500,0.913043,7.375109
13,frozenset({bluetooth headphones}),"frozenset({samsung galaxy 10, airpods})",0.005571,0.079646,7.352465
14,"frozenset({samsung galaxy 10, airpods})",frozenset({bluetooth headphones}),0.005571,0.514286,7.352465
15,frozenset({bluetooth headphones}),"frozenset({airpods, final fantasy XXII})",0.006500,0.092920,7.148230
16,"frozenset({airpods, final fantasy XXII})",frozenset({bluetooth headphones}),0.006500,0.500000,7.148230
17,"frozenset({portal 2, airpods})",frozenset({candy bars}),0.004024,0.317073,7.114329
18,frozenset({candy bars}),"frozenset({portal 2, airpods})",0.004024,0.090278,7.114329
19,"frozenset({bluetooth headphones, airpods})","frozenset({protein bar, energy drink})",0.004952,0.144144,7.056511
20,"frozenset({protein bar, energy drink})","frozenset({bluetooth headphones, airpods})",0.004952,0.242424,7.056511
21,frozenset({bluetooth headphones}),"frozenset({protein bar, energy drink, airpods})",0.004952,0.070796,6.931617
22,"frozenset({protein bar, energy drink, airpods})",frozenset({bluetooth headphones}),0.004952,0.484848,6.931617
23,frozenset({bluetooth headphones}),"frozenset({samsung galaxy 10, energy drink})",0.004333,0.061947,6.901739
24,"frozenset({samsung galaxy 10, energy drink})",frozenset({bluetooth headphones}),0.004333,0.482759,6.901739
25,frozenset({energy drink}),"frozenset({airpods, final fantasy XX})",0.006190,0.070423,6.895006
26,"frozenset({airpods, final fantasy XX})",frozenset({energy drink}),0.006190,0.606061,6.895006
27,frozenset({portal 2}),"frozenset({airpods, candy bars})",0.004024,0.103175,6.803207
28,"frozenset({airpods, candy bars})",frozenset({portal 2}),0.004024,0.265306,6.803207
29,frozenset({bluetooth headphones}),"frozenset({chocolate, airpods})",0.005571,0.079646,6.598366

======================================================================
CLUSTER: Karens
======================================================================

,antecedents,consequents,support,confidence,lift
0,"frozenset({salad, tomatoes})","frozenset({carrots, frozen vegetables})",0.010464,0.101918,2.508738
1,"frozenset({carrots, frozen vegetables})","frozenset({salad, tomatoes})",0.010464,0.257576,2.508738
2,"frozenset({salad, tomatoes})","frozenset({frozen vegetables, spinach})",0.010710,0.104317,2.427975
3,"frozenset({frozen vegetables, spinach})","frozenset({salad, tomatoes})",0.010710,0.249284,2.427975
4,"frozenset({green beans, asparagus, tomatoes})","frozenset({salad, spinach})",0.009356,0.258503,2.399798
5,"frozenset({salad, spinach})","frozenset({green beans, asparagus, tomatoes})",0.009356,0.086857,2.399798
6,"frozenset({salad, tomatoes})","frozenset({carrots, green grapes, asparagus})",0.008741,0.085132,2.392825
7,"frozenset({carrots, green grapes, asparagus})","frozenset({salad, tomatoes})",0.008741,0.245675,2.392825
8,"frozenset({strawberries, frozen vegetables})","frozenset({salad, asparagus})",0.009972,0.402985,2.373784
9,"frozenset({strawberries, green grapes})","frozenset({avocado, spinach})",0.008248,0.250000,2.369603
10,"frozenset({frozen vegetables, asparagus})","frozenset({salad, strawberries})",0.009972,0.145161,2.358290
11,"frozenset({salad, strawberries})","frozenset({frozen vegetables, asparagus})",0.009972,0.162000,2.358290
12,"frozenset({frozen vegetables, avocado})","frozenset({salad, tomatoes})",0.009972,0.241791,2.354998
13,"frozenset({salad, tomatoes})","frozenset({frozen vegetables, avocado})",0.009972,0.097122,2.354998
14,"frozenset({mineral water, spinach})","frozenset({salad, green beans})",0.008494,0.139676,2.353919
15,"frozenset({salad, green beans})","frozenset({mineral water, spinach})",0.008494,0.143154,2.353919
16,"frozenset({frozen vegetables, asparagus})","frozenset({salad, zucchini})",0.010095,0.146953,2.345192
17,"frozenset({salad, zucchini})","frozenset({frozen vegetables, asparagus})",0.010095,0.161100,2.345192
18,"frozenset({mineral water, salad})","frozenset({green beans, spinach})",0.008494,0.139676,2.339359
19,"frozenset({green beans, spinach})","frozenset({mineral water, salad})",0.008494,0.142268,2.339359
20,"frozenset({strawberries, green grapes})","frozenset({salad, avocado})",0.008002,0.242537,2.331515
21,"frozenset({asparagus, zucchini, tomatoes})","frozenset({salad, spinach})",0.008494,0.250909,2.329297
22,"frozenset({carrots, spinach})","frozenset({eggplant, avocado})",0.009725,0.093602,2.318074
23,"frozenset({eggplant, avocado})","frozenset({carrots, spinach})",0.009725,0.240854,2.318074
24,"frozenset({strawberries, asparagus, tomatoes})","frozenset({salad, avocado})",0.008864,0.240803,2.314840
25,"frozenset({salad, avocado})","frozenset({strawberries, asparagus, tomatoes})",0.008864,0.085207,2.314840
26,"frozenset({avocado, tomatoes})","frozenset({carrots, green grapes, asparagus})",0.008494,0.082045,2.306066
27,"frozenset({carrots, green grapes, asparagus})","frozenset({avocado, tomatoes})",0.008494,0.238754,2.306066
28,"frozenset({frozen vegetables, asparagus})","frozenset({salad, tomatoes})",0.016250,0.236559,2.304041
29,"frozenset({salad, tomatoes})","frozenset({frozen vegetables, asparagus})",0.016250,0.158273,2.304041

======================================================================
CLUSTER: Loyal core spenders
======================================================================

,antecedents,consequents,support,confidence,lift
0,frozenset({eggs}),frozenset({cereals}),0.021959,0.236877,2.626763
1,frozenset({cereals}),frozenset({eggs}),0.021959,0.243511,2.626763
2,frozenset({fresh bread}),frozenset({cereals}),0.021497,0.221728,2.458774
3,frozenset({cereals}),frozenset({fresh bread}),0.021497,0.238388,2.458774
4,frozenset({cereals}),frozenset({butter}),0.021898,0.242828,2.380549
5,frozenset({butter}),frozenset({cereals}),0.021898,0.214674,2.380549
6,frozenset({butter}),frozenset({eggs}),0.022483,0.220411,2.377579
7,frozenset({eggs}),frozenset({butter}),0.022483,0.242525,2.377579
8,frozenset({airpods}),frozenset({energy drink}),0.027688,0.189144,2.336875
9,frozenset({energy drink}),frozenset({airpods}),0.027688,0.342085,2.336875
10,frozenset({airpods}),frozenset({bluetooth headphones}),0.027996,0.191248,2.275419
11,frozenset({bluetooth headphones}),frozenset({airpods}),0.027996,0.333089,2.275419
12,frozenset({eggs}),frozenset({fresh bread}),0.020450,0.220598,2.275285
13,frozenset({fresh bread}),frozenset({eggs}),0.020450,0.210928,2.275285
14,frozenset({butter}),frozenset({fresh bread}),0.020573,0.201691,2.080273
15,frozenset({fresh bread}),frozenset({butter}),0.020573,0.212198,2.080273

======================================================================
CLUSTER: Tech enthusiasts
======================================================================

,antecedents,consequents,support,confidence,lift
0,frozenset({energy drink}),"frozenset({airpods, gadget for tiktok streaming})",0.007690,0.093074,6.347165
1,"frozenset({airpods, gadget for tiktok streaming})",frozenset({energy drink}),0.007690,0.524390,6.347165
2,frozenset({bluetooth headphones}),"frozenset({brownies, airpods})",0.006438,0.097035,6.309534
3,"frozenset({brownies, airpods})",frozenset({bluetooth headphones}),0.006438,0.418605,6.309534
4,"frozenset({energy drink, airpods})",frozenset({gadget for tiktok streaming}),0.007690,0.226316,5.805311
5,frozenset({gadget for tiktok streaming}),"frozenset({energy drink, airpods})",0.007690,0.197248,5.805311
6,"frozenset({energy drink, gadget for tiktok str...",frozenset({airpods}),0.007690,0.661538,5.579673
7,"frozenset({energy drink, iphone 10})",frozenset({airpods}),0.009120,0.629630,5.310541
8,"frozenset({energy drink, airpods})",frozenset({bluetooth headphones}),0.011803,0.347368,5.235806
9,frozenset({bluetooth headphones}),"frozenset({energy drink, airpods})",0.011803,0.177898,5.235806
10,"frozenset({bluetooth headphones, pancakes})",frozenset({airpods}),0.006617,0.606557,5.115941
11,"frozenset({energy drink, airpods})",frozenset({iphone 10}),0.009120,0.268421,5.070982
12,frozenset({iphone 10}),"frozenset({energy drink, airpods})",0.009120,0.172297,5.070982
13,"frozenset({airpods, iphone 10})",frozenset({energy drink}),0.009120,0.414634,5.018689
14,frozenset({energy drink}),"frozenset({airpods, iphone 10})",0.009120,0.110390,5.018689
15,"frozenset({brownies, bluetooth headphones})",frozenset({airpods}),0.006438,0.590164,4.977672
16,"frozenset({energy drink, pancakes})",frozenset({airpods}),0.007153,0.588235,4.961405
17,"frozenset({energy bar, energy drink})",frozenset({bluetooth headphones}),0.006974,0.325000,4.898652
18,frozenset({bluetooth headphones}),"frozenset({energy bar, energy drink})",0.006974,0.105121,4.898652
19,frozenset({bluetooth headphones}),"frozenset({airpods, pancakes})",0.006617,0.099730,4.892041
20,"frozenset({airpods, pancakes})",frozenset({bluetooth headphones}),0.006617,0.324561,4.892041
21,frozenset({airpods}),"frozenset({bluetooth headphones, energy drink})",0.011803,0.099548,4.883067
22,"frozenset({bluetooth headphones, energy drink})",frozenset({airpods}),0.011803,0.578947,4.883067
23,"frozenset({bluetooth headphones, energy bar})",frozenset({energy drink}),0.006974,0.402062,4.866515
24,frozenset({energy drink}),"frozenset({bluetooth headphones, energy bar})",0.006974,0.084416,4.866515
25,"frozenset({bluetooth headphones, iphone 10})",frozenset({airpods}),0.006795,0.558824,4.713335
26,"frozenset({airpods, iphone 10})",frozenset({bluetooth headphones}),0.006795,0.308943,4.656630
27,frozenset({bluetooth headphones}),"frozenset({airpods, iphone 10})",0.006795,0.102426,4.656630
28,"frozenset({bluetooth headphones, airpods})",frozenset({energy drink}),0.011803,0.383721,4.644518
29,frozenset({energy drink}),"frozenset({bluetooth headphones, airpods})",0.011803,0.142857,4.644518

======================================================================
CLUSTER: Vegans
======================================================================

,antecedents,consequents,support,confidence,lift
0,"frozenset({babies food, napkins})",frozenset({cooking oil}),0.015739,0.357704,2.624588
1,frozenset({cooking oil}),"frozenset({babies food, napkins})",0.015739,0.115482,2.624588
2,frozenset({napkins}),"frozenset({dog food, cooking oil})",0.015843,0.112008,2.613426
3,"frozenset({dog food, cooking oil})",frozenset({napkins}),0.015843,0.369653,2.613426
4,frozenset({napkins}),"frozenset({babies food, cooking oil})",0.015739,0.111274,2.606827
5,"frozenset({babies food, cooking oil})",frozenset({napkins}),0.015739,0.368720,2.606827
6,"frozenset({dog food, napkins})",frozenset({cooking oil}),0.015843,0.350689,2.573115
7,frozenset({cooking oil}),"frozenset({dog food, napkins})",0.015843,0.116244,2.573115
8,frozenset({energy drink}),frozenset({airpods}),0.013076,0.209767,2.517290
9,frozenset({airpods}),frozenset({energy drink}),0.013076,0.156912,2.517290
10,"frozenset({dog food, toilet paper})",frozenset({napkins}),0.010101,0.355231,2.511464
11,frozenset({napkins}),"frozenset({dog food, babies food})",0.016327,0.115432,2.466381
12,"frozenset({dog food, babies food})",frozenset({napkins}),0.016327,0.348854,2.466381
13,"frozenset({dog food, babies food})",frozenset({cooking oil}),0.015635,0.334072,2.451193
14,frozenset({cooking oil}),"frozenset({dog food, babies food})",0.015635,0.114721,2.451193
15,frozenset({babies food}),"frozenset({cooking oil, napkins})",0.015739,0.102570,2.422543
16,"frozenset({cooking oil, napkins})",frozenset({babies food}),0.015739,0.371732,2.422543
17,"frozenset({napkins, toilet paper})",frozenset({dog food}),0.010101,0.397820,2.421685
18,frozenset({babies food}),"frozenset({dog food, cooking oil})",0.015635,0.101894,2.377435
19,"frozenset({dog food, cooking oil})",frozenset({babies food}),0.015635,0.364810,2.377435
20,frozenset({babies food}),"frozenset({dog food, napkins})",0.016327,0.106402,2.355268
21,"frozenset({dog food, napkins})",frozenset({babies food}),0.016327,0.361409,2.355268
22,frozenset({airpods}),frozenset({bluetooth headphones}),0.012142,0.145704,2.322021
23,frozenset({bluetooth headphones}),frozenset({airpods}),0.012142,0.193495,2.322021
24,"frozenset({cooking oil, napkins})",frozenset({dog food}),0.015843,0.374183,2.277797
25,"frozenset({babies food, napkins})",frozenset({dog food}),0.016327,0.371069,2.258842
26,"frozenset({babies food, cooking oil})",frozenset({dog food}),0.015635,0.366288,2.229740
27,frozenset({napkins}),frozenset({cooking oil}),0.042340,0.299340,2.196348
28,frozenset({cooking oil}),frozenset({napkins}),0.042340,0.310660,2.196348
29,"frozenset({dog food, napkins})",frozenset({toilet paper}),0.010101,0.223583,2.119900

In [44]:
#customer_merged = pd.merge(
 #   customer_basket, 
  #  customer[['customer_id', 'final_cluster_label']], 
   # on='customer_id', 
    #how='inner')
#customer_merged

Note: some baskets were lost due to outlier removal.


**Temos q ver como fazemos com isto, se so aceitamos ou corremos os notebooks todos com os outliers mm**